### PR TITLE
Closes #2

### LINKED ISSUE #2: markup product page

### PR DESCRIPTION
**Pull request by dbarabashdev**
## Please verify the following:		 
**Make sure these boxes are checked before submitting pull request.**
 - [x] Everything locally		
 - [x] According to design (pixel perfect)
 - [x] Front-end is according to the design (if applicable)		
- [x] Ask designer to validate correctness
 - [x] Check that vertical scaling aligns with expectations
 - [x] Cross-browser
   - [x] Chrome
   - [x] Safari
   - [x] Firefox
 - [x] Cross-platform
   - [x] Mac
   - [x] Windows
 - [x] Screen dimensions
   - [x] Mobile
   - [x] Tablet
   - [x] Desktop
  - [x] 2560 x 1440
  - [x] 1920 x 1080
  - [x] 1366 x 768
  - [x] 1280 x 800
  - [x] 1432 x 672
 - [x] Check letter spacing
 - [x] Check font smoothing & text rendering

### CODE REVIEW

**Comment by dbarabashdev** [comment]
http://fci.new-product-page.stage.surge.sh/product.html

**Comment by RomanTsegelskyi** [comment]
@aliciaclarkeFCI regarding 7, can you please resend them in crew. Regarding 6, when will you be able to send that? We can also just put the link and the PDF can be added later

**Comment by aliciaclarkeFCI** [comment]
Attached is the PDF  that should be opened on a new page when viewers click "Download Spec Sheet"
 [DeltaP SmartValve Spec Sheet 2 PAGER_06072017.pdf](https://github.com/FlowEnergy/fci.com/files/1380066/DeltaP.SmartValve.Spec.Sheet.2.PAGER_06072017.pdf)

**Comment by dbarabashdev** [comment]
- [] Under "What makes our solution different?" >> Next Gen HVAC Tech, each bullet point should end in a period (like the other tabs). Also, the last bullet has a colon at the end. This should not be there.
- [] Under "What makes our solution different?" >> Guaranteed Performance, the last two bullet points also don't have periods at the end. Please add those.
There needs to be a space in the title "DeltaP Smartvalve® Sensors" between "®" and "Sensors".
- [] For the "DeltaP Smartvalve® Sensors" boxes, please make sure the bullet points that run onto two lines are equally indented on the second line. It looks good on the FCI Advantage bullet points, but the sensor bullet points are aligned the same way. Please indent the second line on those bullet points to match the FCI Advantage ones.
- [] "DeltaP Smartvalve®Spec Sh" should say "DeltaP Smartvalve® Spec Sheet". Please add a space between "®" and "Spec", and complete the last word, "Sheet".
- [] The "Download Spec Sheet" button needs to lead to a PDF, which I'll send.
- [] The images in the product carousel are still wrong. I sent each image in crew.co, with the appropriate caption as the caption of the image. Please tell me if you did not get this and I can re-send in whatever format you prefer.

**Pull request merged**
