### PR TITLE
New product page

### PR DESCRIPTION
**Pull request by andriytsaryov**
http://meaty-quiver.surge.sh/product-2.html

### CODE REVIEW

**Comment by aliciaclarkeFCI** [comment]
Hi there! The product page is looking good. Just a few more notes...

1.	In the “What makes our solution different?” section, when the text spills on to two lines, can it be indented so that it lines up with the other text, not the bullet point? (see image "website indents p2") 
2.	In the “DeltaP SmartValve® Sensors” section, when the text spills on to two lines, can it also be indented so that it lines up with the other text, not the bullet point? (see image "website indents")
3.	Will the spec sheet be uploaded as a PDF in a separate window (not working right now)?
4.	For the product image carousel, the please only include the following image ONCE, with the caption, ‘10”, 12”, 14”, & 16” KDP DeltaP SmartValve”.
5.	The photos for the 3” HDP valve, 6” EDP valve, and 8” IDP valve all look distorted. Can this be fixed?

**Comment by aliciaclarkeFCI** [comment]
website indents p2

**Comment by aliciaclarkeFCI** [comment]
website indents

**Comment by andriytsaryov** [comment]
Hi @aliciaclarkeFCI,

I've fixed all the notes you wrote above, the updated version of the page has been uploaded to http://meaty-quiver.surge.sh/product-2.html, you can check it out.

Some notes on the 4th point, PDF does not open due to limitations of the test playground (surge.sh), where the site was uploaded temporarily.

Thanks.

**Comment by chrisjones117** [comment]
Andriytsaryov,

I've pulled this code down and I'm trying to build, but when running 'gulp build' I get the following errors:

```
events.js:182
      throw er; // Unhandled 'error' event
      ^
Error: /home/chris2/aws-git/flowcontrol.com/build/jade/page/product-delta.jade:103
    101|     .container
    102|      .hidden-sm.hidden-xs.product-wrap-carousel
  > 103|       include ../../jade/includes/product-carousel
    104| 
    105|     .product-scroll-wrap.customers-scroll-wrap.visible-sm.visible-xs
    106|       .customers-scroll

ENOENT: no such file or directory, open '/home/chris2/aws-git/flowcontrol.com/build/jade/includes/product-carousel.jade'
    at Object.fs.openSync (fs.js:648:18)
    at Object.fs.readFileSync (fs.js:553:33)
    at Parser.parseInclude (/home/chris2/node_modules/jade/lib/parser.js:606:18)
    at Parser.parseExpr (/home/chris2/node_modules/jade/lib/parser.js:223:21)
    at Parser.block (/home/chris2/node_modules/jade/lib/parser.js:729:25)
    at Parser.tag (/home/chris2/node_modules/jade/lib/parser.js:838:24)
    at Parser.parseTag (/home/chris2/node_modules/jade/lib/parser.js:759:17)
    at Parser.parseExpr (/home/chris2/node_modules/jade/lib/parser.js:211:21)
    at Parser.parseExpr (/home/chris2/node_modules/jade/lib/parser.js:252:21)
    at Parser.block (/home/chris2/node_modules/jade/lib/parser.js:729:25)
```
Do you know what the problem might be, or what I can do to get beyond it? I'm just trying to generate the finished HTML and assets to publish to our site.

Thanks

**Pull request merged**
